#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

#cursor-theme
hyprctl setcursor Bibata-Modern-Classic 10
gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Classic

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
#$scripts/wall $config/wallpapers/japanese-art.jpg &

# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
