#!/bin/env sh

FUZZEL_PATH=$HOME/.config/hypr/fuzzel/
FUZZEL_CACHE_PATH=$FUZZEL_PATH/.cache/

emojis=$(cat <"$FUZZEL_PATH/unicode")

emoji=$(
	echo "$emojis" | fuzzel --cache "$FUZZEL_CACHE_PATH/unicode" \
		-w 20 -di
) || exit 0

echo "$emoji" | cut -d ' ' -f1 | tr -d '\n' | wl-copy &&
	notify-send "Emoji copied to clipboard" "$emoji"
