#!/usr/bin/env bash

img_dir=~/Pictures/wallpapers
resolution="1920x1080"
query="evening,clouds"
unsplash_access_key="nErTkpUR8qykyoPDuF7WpLoQXL3DQqsKlVbYWLmH2mg"
current_time=$(date +"%Y-%m-%d_%H-%M-%S")
output_path="$img_dir/$current_time.jpg"

mkdir -p "$img_dir"
find "$img_dir" -type f -mtime +1 -delete

api_url="https://api.unsplash.com/photos/random?query=${query}&orientation=landscape&client_id=${unsplash_access_key}"
image_url=$(curl -s "$api_url" | jq -r '.urls.full')

if [[ "$image_url" == "null" || -z "$image_url" ]]; then
    echo "Failed to get image URL from Unsplash API"
    exit 1
fi

wget -q "$image_url" -O "$output_path"

if [ -f "$output_path" ]; then
    swww img "$output_path"
    echo "Changed wallpaper image successfully"
else
    echo "Failed to download wallpaper"
    exit 1
fi

