theme = "tokyonight_day"

[editor]
line-number = 'relative'
end-of-line-diagnostics = "hint"

[editor.cursor-shape] 
insert = "bar"

[editor.file-picker]
hidden = false

[keys.insert]
j = { k = "normal_mode" }
[editor.inline-diagnostics]
cursor-line = "warning"
